// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbD2dz3AWJOBcb3qJI8ElV3Q4FfuajbQ',
    appId: '1:67747794201:web:134eadea143523e429c988',
    messagingSenderId: '67747794201',
    projectId: 'room-booking-app-aus-2026',
    authDomain: 'room-booking-app-aus-2026.firebaseapp.com',
    storageBucket: 'room-booking-app-aus-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc_ygbPXmMQe-ZPwykGU3ulD7uvw2lDCs',
    appId: '1:67747794201:android:c2c742bdcfaba6bd29c988',
    messagingSenderId: '67747794201',
    projectId: 'room-booking-app-aus-2026',
    storageBucket: 'room-booking-app-aus-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PpXQ4kv28KZASJd2_HvHWy_wasg_8ts',
    appId: '1:67747794201:ios:b3c7e310c0c8fa6829c988',
    messagingSenderId: '67747794201',
    projectId: 'room-booking-app-aus-2026',
    storageBucket: 'room-booking-app-aus-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PpXQ4kv28KZASJd2_HvHWy_wasg_8ts',
    appId: '1:67747794201:ios:b3c7e310c0c8fa6829c988',
    messagingSenderId: '67747794201',
    projectId: 'room-booking-app-aus-2026',
    storageBucket: 'room-booking-app-aus-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbD2dz3AWJOBcb3qJI8ElV3Q4FfuajbQ',
    appId: '1:67747794201:web:015e2eb81a6dd20829c988',
    messagingSenderId: '67747794201',
    projectId: 'room-booking-app-aus-2026',
    authDomain: 'room-booking-app-aus-2026.firebaseapp.com',
    storageBucket: 'room-booking-app-aus-2026.firebasestorage.app',
  );
}
